### ISSUE TITLE
ログイン機能の実装

### ISSUE THREAD

**Issue by kota22** [skykataoka/akiya_etajima#15]
- [ ] 現在つくられているUser Modelを消す
- [ ] gem 'devise'を使い、deviseによって生成されたUser Modelを作成する。

**Comment by skykataoka** [comment]
実装完了しました。
seedデータからダミーデータを作りたいのですが
'devise'のUser Modelと干渉してうまくいかないようです。こちら修正可能でしょうか??

**Comment by kota22** [comment]
後日seedデータ修正します。
